### ISSUE TITLE
scipy solver prematurely stopped due to divergence

### ISSUE THREAD

**Issue by cassiofragadantas** [benchopt/benchmark_nnls#10]
**Maybe this should be an issue in the benchopt main repository, since it involves the divergence identification criterion in benchopt/stopping_criterion.py**

By running, for instance, the following benchmark (same issue happens with other datasets):
`$ benchopt run -e . -d Simulated -s cd -s scipy`

I obtain the following output:
```
Benchopt is running
Simulated[n_features=5000,n_samples=100]                                                                                                                                                                   
  |--Non Negative Least Squares[fit_intercept=False]                                                                                                                                                       
    |--cd: done                                                                                                                                                                                            
    |--scipy: diverged
```
Scipy solver is stopped due to divergence. However, it does not really diverge and this can be verified by manually deactivating divergence detection in 'benchopt/stopping_criterion.py' line 197 as follows:
`if math.isnan(objective_value): # or delta_objective < -1e5:  `

The following results are then obtained:
![Screenshot from 2022-07-08 15-05-39](https://user-images.githubusercontent.com/774058/177997789-2a7a9aea-b44a-44c8-89c4-4685c63cbc96.png)

Indeed, we see that the objective function increases on initial iterations, which is currently identified as divergence by benchopt.

**Comment by tomMoral** [comment]
Yes, this was an issue with benchopt and this should be corrected with benchopt/benchopt#435
the issue was with the negative objective, that flipped the sign of the test I think.
can you check that this is solved with benchopt master?

**Comment by cassiofragadantas** [comment]
Unfortunately, it doesn't solve the problem.
However, I think I figured out the issue and it won't require modifying benchopt/stopping_criterion.py.

By checking the scipy code for nnls (it's in Fortran...), they redefine the maximum number of iterations to a big value  whenever $\mathrm{maxiter} \leq 0$ (see [lines 73-77](https://github.com/scipy/scipy/blob/v1.8.1/scipy/optimize/__nnls/nnls.f)). Then, the cost function at iteration 0, which is used by benchopt to detect divergence, is already very low.

**Proposed solution**: start scipy solver at `n_iter=1`. I'll do a pull request with this.

**Comment by cassiofragadantas** [comment]
Solved by #13
